# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [17]:
#determina si ninguno de los elementos es cero.
a = np.array([1, 2, 3, 4])
respuesta = np.any(a == 0)
print(respuesta)

False


In [19]:
# ejercicio 2 determina si contiene algún elemento que no sea cero.
a = np.array([0, 0, 2, 0])
respuesta = np.any (a!=0)
print (respuesta)

True


In [22]:
#determina si contiene valores que sean infinitos o valores no numéricos (NaN).
a = np.array([1, 2, np.nan, np.inf])
mascara_inf = np.isinf(a)
print(mascara_inf)
mascara_validos = np.isfinite(a)
print(mascara_validos)

[False False False  True]
[ True  True False False]


In [24]:
#4 determina si contiene valores infinitos.
a = np.array([1, 2, np.inf])
respuesta = np.any(np.isinf(a))
print(respuesta)

True


In [27]:
#5 determina si contiene valores NaN.
a = np.array([1, np.nan, 3])
respuesta = np.any (np.isnan(a))
print (respuesta)

True


In [40]:
# 6 realiza una comparación elemento a elemento 
# contemplando mayor, mayor o igual, menor y menor o igual.
del print
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
mayores = (a > b)
print (mayores)
mayor_o_igual = (a >= b)
print(mayor_o_igual)
menor = (a <= b)
print (menor)




[False False  True]
[False  True  True]
[ True  True False]


In [41]:
#7 determina la cantidad de memoria que ocupa el arreglo.
a = np.array ([1, 7, 13, 105])
memoria = a.nbytes
print (memoria)

32


In [46]:
#8 Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
del print
cero = np.zeros(10)
print (cero)
uno = np.ones(10)
print (uno)
cinco = np.full (10, 5)
print (cinco)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [47]:
#9 Crea un arreglo que contenga todos los números enteros entre 30 y 70.
a = np.arange(30, 70)
print (a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [49]:
#10 Crea un arreglo que contenga los números pares entre 30 y 70.
a = np.arange (30, 70, 2)
print (a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [50]:
#Crea una matriz identidad de 3x3.
a = np.eye (3)
print (a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
#12 Genera un número aleatorio entre 0 y 1.
rng = np.random.default_rng()
a = rng.random()
print (a)

0.6527386247901489


In [ ]:
#13 Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
rng = np.random.default_rng()
a = rng.normal (size=15)
print (a)

[ 1.63676774 -0.49281281  0.23476829 -1.11713894 -0.67896507  0.33056036
 -0.6079466  -0.80791837 -0.60602643  0.04744835  0.84164451 -0.69379353
 -0.70941389 -0.54829331  0.75709216]


In [73]:
#14Crea un arreglo con valores entre 15 y 55, e imprime todos los 
# valores excepto el primero y el último.
a = np.arange (15, 55)
sin = np.delete(a, [0, -1])
print (sin)

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [77]:
#15 Crea un vector (arreglo) de longitud 10 con
#  valores equitativamente distribuidos entre 5 y 50.
a = np.linspace (5, 50, 10)
print (a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [80]:
#16 Crea un vector con valores de 0 a 20, y cambia el signo de 
# los números  de 9 a 15.
a = np.arange (0,21)
a[9:16] = a[9:16]*-1
print (a)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [ ]:
#17 Convierte el arreglo a = np.array([1, 2, 3]) 
# a una lista de Python.
a = np.array([1, 2, 3]) 
lista = a.tolist()
print (a)

[1 2 3]


In [84]:
#18 Convierte la lista l = [1, 2, 3] a un arreglo de Numpy.
l = [1, 2, 3] 
a = np.array(l)
print (a)

[1 2 3]


In [86]:
#19 Dada la matriz m = np.array([[1, 2], [3, 4]]), verifica qué 
# números son pares y almacena los resultados en otra matriz.
m = np.array([[1, 2], [3, 4]])
pares = (m % 2 == 0)
print (pares)

[[False  True]
 [False  True]]


In [89]:
#20 Dado el arreglo m = np.array([[1, 2, 3], [4, 5, 6]]), 
# encuentra el número de filas y columnas de la matriz.
m = np.array([[1, 2, 3], [4, 5, 6]])
filas_y_columnas = m.shape
print (filas_y_columnas)

(2, 3)
